### ISSUE TITLE
Not functioning while debugging from Flash Builder 4.0

### ISSUE THREAD

**Issue by Ansury** [doublefx/easyWorker#8]
The "addition" example (TermsVo) does not work when debugging from FB 4.  While I realize this is not exactly a supported IDE with Apache Flex 4.14, I'm not sure if this applies to all later versions of FB.  This happens both debugging within AIR (16.0) and Flash (latest as of today), but the thread works fine on BOTH platforms when not attempting to attach the debugger (using Run).  

Running the example, the Start button is disabled with thread "Running" and no result displayed. (debug mode)  If not running in debug mode, the Start button is enabled and a result is displayed when clicked.  Couldn't find any mention of this being a known issue anywhere.

Note - due to the broken swc download I had to compile the library myself; if doing something wrong there is a possible cause of the problem let me know and I'll look into it further.

**Comment by doublefx** [comment]
Sorry for the delay, I was sure I answered it.

Did you try with the compiler argument: -optimize=false

**Comment by Ansury** [comment]
Even with -optimize=false it's doing the same, everything (and the start button) is disabled, but only when running in debug mode.

**Comment by doublefx** [comment]
FB 4.6 and 4.7 dont use FDB Command line internaly but a higher level API, Im not that much surprised it doesnt work on 4.6 and I'm curious how it works on 4.7, should be better though as the higher level API is supposed to handle it even though it has its own implementation to break into which is not the one of the command line version.

With Intellij it works, not perfectly as they didnt do any particular development to support the feature yet but because internally they use FDB, it works more naturally.

I dont use Flash Develop but it seems they added support to it.

**Comment by Ansury** [comment]
Actually I'm using FB 4 - as in 4.0.
